env:
  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: login in acr and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build --file ./docker-prod/Dockerfile -t nodeapp:1 .
          docker tag nodeapp:1 ${{ secrets.ACR_LOGIN_SERVER }}:node
          docker push ${{ secrets.ACR_LOGIN_SERVER }}:node
