env:
  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build --file ./docker-prod/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER}}:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER}}:${{ github.sha }}
